server:
  port: 8080
spring:
  application:
    name: demo-service
  datasource:
    url: jdbc:h2:mem:testdb;Mode=Oracle
    driver-class-name: org.h2.Driver
    username: sa
    password:

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always

vaadin:
  # Ensure application is run in Vaadin 14/npm mode
  compatibilityMode: false

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
