# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [1.8, 11, 14]
    steps:
    - uses: actions/checkout@v2
    - name: Set up java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: | 
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -Pproduction clean install
    - name: Archive demo-service
      uses: actions/upload-artifact@v1
      with:
        name: demo-service.jar
        path: demo-service/target/demo-service-1.0.0-SNAPSHOT-exec.jar     
